### PR TITLE
Feature: network download tests

### PR DESCRIPTION
**Pull request by screamerbg**
This PR introduces network download tests in TESTS/network/ to cover the following test cases:
* Single HTTP download stream in main loop (technically main thread) with 256 bytes, 1kb, 2kb, 4kb, 8kb, 16kb and 32kb receive buffer.
* Multiple concurrent HTTP download streams with 1, 2, 3 and 4 threads which are separate to main loop / thread. 

The tests use the Github.io hosted files of https://github.com/ARMmbed/mbed-test-files repository.

Based on @marcuschangarm's work from https://github.com/ARMmbed/mbed-stress-test which makes use of raw TCP sockets.

CC @MarceloSalazar @bridadan

Below is an example output

```
mbedgt: test suite report:
+-------------------------+---------------------+------------------------------------------------------+--------+--------------------+-------------+
| target                  | platform_name       | test suite                                           | result | elapsed_time (sec) | copy_method |
+-------------------------+---------------------+------------------------------------------------------+--------+--------------------+-------------+
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-main     | OK     | 48.6               | default     |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-threaded | OK     | 64.39              | default     |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | OK     | 140.58             | default     |
+-------------------------+---------------------+------------------------------------------------------+--------+--------------------+-------------+
mbedgt: test suite results: 3 OK
mbedgt: test case report:
+-------------------------+---------------------+------------------------------------------------------+----------------------------+--------+--------+--------+--------------------+
| target                  | platform_name       | test suite                                           | test case            | passed | failed | result | elapsed_time (sec) |
+-------------------------+---------------------+------------------------------------------------------+----------------------------+--------+--------+--------+--------------------+
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-main     | Download  1k recv buffer   | 1      | 0      | OK     | 3.05               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-main     | Download  2k recv buffer   | 1      | 0      | OK     | 2.8                |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-main     | Download  4k recv buffer   | 1      | 0      | OK     | 3.2                |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-main     | Download  8k recv buffer   | 1      | 0      | OK     | 2.77               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-main     | Download 16k recv buffer   | 1      | 0      | OK     | 2.76               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-main     | Download 32k recv buffer   | 1      | 0      | OK     | 2.75               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-main     | Setup network              | 1      | 0      | OK     | 3.88               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-threaded | Download 1 thread          | 1      | 0      | OK     | 2.98               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-threaded | Download 2 threads         | 1      | 0      | OK     | 6.4                |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-threaded | Download 3 threads         | 1      | 0      | OK     | 9.7                |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-threaded | Download 4 threads         | 1      | 0      | OK     | 14.18              |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-network-http-threaded | Setup network              | 1      | 0      | OK     | 3.68               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | Connect to Network         | 1      | 0      | OK     | 3.85               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | Consistent Identity        | 1      | 0      | OK     | 2.43               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | Format Storage             | 1      | 0      | OK     | 27.48              |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | LwM2M GET Test             | 1      | 0      | OK     | 1.31               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | LwM2M POST Test            | 1      | 0      | OK     | 0.47               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | LwM2M PUT Test             | 1      | 0      | OK     | 0.8                |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | LwM2M SET Test             | 1      | 0      | OK     | 0.44               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | Pelion DM Directory        | 1      | 0      | OK     | 7.24               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | Pelion DM Register         | 1      | 0      | OK     | 6.41               |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-simple-connect        | Simple PDMC Initialization | 1      | 0      | OK     | 3.58               |
+-------------------------+---------------------+------------------------------------------------------+----------------------------+--------+--------+--------+--------------------+
mbedgt: test case results: 22 OK
mbedgt: completed in 255.04 sec
```

### CODE REVIEW

**Comment by screamerbg** [comment]
Here's a detailed log - [network-tests-detailed.log](https://github.com/ARMmbed/simple-mbed-cloud-client/files/2497328/network-tests-detailed.log)

**Comment by screamerbg** [comment]
Updated log with latest output (added size and download speed for debugging purposes) - 
[network-tests-detailed.log.txt](https://github.com/ARMmbed/simple-mbed-cloud-client/files/2502331/network-tests-detailed.log.txt)

**Comment by MarceloSalazar** [comment]
This looks really good, thanks for the PR :)
Would it be possible to add tests for http_**s**_? If not here, maybe on a separate PR?
This is important to ensure we test TLS as well. Thanks!

**Comment by screamerbg** [comment]
Closing this in favour of new PR

**Pull request closed without merging**
