### PR TITLE
Add simple malloc test to verify there is a min amount of memory

### PR DESCRIPTION
**Pull request by maclobdell**
### Background
The idea for this update is to have the system connect to the network and setup the storage, then see how much memory can be allocated.  If successful, it will free the memory.  Ideally we could characterize the exact limit on many devices, but for GreenTea, we can only do pass/fail tests.  So, it stopped it at 40K, but it as a reasonable minimum.  

### Possible Improvements
The test can be updated to try to allocate more or less.  Also, it could allocate smaller chunks iteratively if it is determined that fragmentation is limiting the available memory in large chunks. 

### Test results
This has been tested on just a few devices such as K64 and K66.

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
This is awesome, thanks Mac!
I'm curious about the fragmentation and whether it would make more sense to allocate multiple chunks of 1/5/10K, instead of one big one (of 20/40/80K). This could let us know how many LwM2M resources could be allocated. Anyway, maybe this is something for later.

**Comment by screamerbg** [comment]
@maclobdell This is awesome! I'll run this against all the boards and let you know of the results.

**Comment by screamerbg** [comment]
Great!

Passed on all currently supported Pelion boards (ignore the Nuvoton IOT failure, it's unrelated to the memory test).
```
2019-02-16 18:58:52 TEST SUMMARY PER TARGET-TOOLCHAIN:
+-------------------------+----------------------------------------------------+--------+--------+
| target/toolchain        | test suite                                         | result |   time |
+-------------------------+----------------------------------------------------+--------+--------+
| DISCO_F413ZH-ARM        | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  61.49 |
| DISCO_F746NG-ARM        | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  77.32 |
| DISCO_F769NI-ARM        | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  51.16 |
| DISCO_L475VG_IOT01A-ARM | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  66.15 |
| EFM32GG11_STK3701-ARM   | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  69.18 |
| GR_LYCHEE-ARM           | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  96.68 |
| K64F-ARM                | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  91.33 |
| K66F-ARM                | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  79.52 |
| MTB_MXCHIP_EMW3166-ARM  | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  97.25 |
| MTB_USI_WM_BN_BM_22-ARM | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     | 102.66 |
| NUCLEO_F207ZG-ARM       | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  71.12 |
| NUCLEO_F429ZI-ARM       | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  80.75 |
| NUCLEO_F746ZG-ARM       | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  74.16 |
| NUCLEO_F767ZI-ARM       | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  70.56 |
| NUMAKER_IOT_M487-ARM    | simple-mbed-cloud-client-tests-basic-stress-net-fs | FAIL   |  31.99 |
| NUMAKER_PFM_M487-ARM    | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  66.65 |
| NUMAKER_PFM_NUC472-ARM  | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  62.13 |
| SDT64B-ARM              | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  88.43 |
| UBLOX_C030_U201-ARM     | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     | 265.25 |
| UBLOX_EVK_ODIN_W2-ARM   | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     | 146.32 |
+-------------------------+----------------------------------------------------+--------+--------+
```

Perhaps a good question is whether the 80k test should be enabled.

**Comment by screamerbg** [comment]
@maclobdell I've manually enabled the 80k case, but all 128K RAM platforms are failing perhaps this could be tuned to 60k RAM?

```
2019-02-16 20:48:41 TEST SUMMARY PER TARGET:
+---------------------+----------------------------------------------------+--------+--------+
| target              | test suite                                         | result |   time |
+---------------------+----------------------------------------------------+--------+--------+
| DISCO_F413ZH        | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  58.91 |
| DISCO_F746NG        | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  75.84 |
| DISCO_F769NI        | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  51.65 |
| DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-basic-stress-net-fs | FAIL   |  34.51 |
| EFM32GG11_STK3701   | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  69.69 |
| GR_LYCHEE           | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  97.36 |
| K64F                | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  94.19 |
| K66F                | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  82.91 |
| MTB_MXCHIP_EMW3166  | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  99.01 |
| MTB_USI_WM_BN_BM_22 | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     | 101.17 |
| NUCLEO_F207ZG       | simple-mbed-cloud-client-tests-basic-stress-net-fs | FAIL   |  29.58 |
| NUCLEO_F429ZI       | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  78.42 |
| NUCLEO_F746ZG       | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  73.27 |
| NUCLEO_F767ZI       | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  68.68 |
| NUMAKER_IOT_M487    | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK   |  60.41 |
| NUMAKER_PFM_M487    | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  60.63 |
| NUMAKER_PFM_NUC472  | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |   62.1 |
| SDT64B              | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     |  86.09 |
| UBLOX_C030_U201     | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     | 265.15 |
| UBLOX_EVK_ODIN_W2   | simple-mbed-cloud-client-tests-basic-stress-net-fs | OK     | 146.65 |
+---------------------+----------------------------------------------------+--------+--------+
```

**Comment by screamerbg** [comment]
Added 60K test case. Thanks much @maclobdell! LGTM.

**Pull request merged**
