### PR TITLE
Update: Pelion DM Client to v2.1.0

### PR DESCRIPTION
**Pull request by screamerbg**
Test results below

```
[2018-12-18 23:32:06] INFO: TEST SUMMARY PER TARGET:

+---------------------+-------------------------------------------------+---------+---------+
| target              | test suite                                      | result  |    time |
+---------------------+-------------------------------------------------+---------+---------+
| DISCO_F413ZH        | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   81.68 |
| DISCO_F413ZH        | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |   168.1 |
| DISCO_F746NG        | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  113.03 |
| DISCO_F746NG        | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  187.45 |
| DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   84.68 |
| DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  170.64 |
| GR_LYCHEE           | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   94.83 |
| GR_LYCHEE           | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  269.09 |
| K64F                | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |    87.8 |
| K64F                | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  174.73 |
| K66F                | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   81.78 |
| K66F                | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  161.17 |
| MTB_MXCHIP_EMW3166  | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  101.73 |
| MTB_MXCHIP_EMW3166  | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  237.61 |
| MTB_USI_WM_BN_BM_22 | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  110.27 |
| MTB_USI_WM_BN_BM_22 | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  310.98 |
| NUCLEO_F429ZI       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |    69.5 |
| NUCLEO_F429ZI       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  161.56 |
| NUCLEO_F746ZG       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   63.77 |
| NUCLEO_F746ZG       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  143.39 |
| NUCLEO_F767ZI       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   61.32 |
| NUCLEO_F767ZI       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  146.31 |
| NUMAKER_IOT_M487    | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   58.06 |
| NUMAKER_IOT_M487    | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  185.47 |
| NUMAKER_PFM_M487    | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   63.74 |
| NUMAKER_PFM_M487    | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |   134.0 |
| NUMAKER_PFM_NUC472  | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  140.38 |
| NUMAKER_PFM_NUC472  | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  228.56 |
| REALTEK_RTL8195AM   | simple-mbed-cloud-client-tests-dev_mgmt-connect | TIMEOUT |  304.56 |
| REALTEK_RTL8195AM   | simple-mbed-cloud-client-tests-dev_mgmt-update  | TIMEOUT |  196.85 |
| SDT64B              | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   89.21 |
| SDT64B              | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |   181.1 |
| UBLOX_C030_U201     | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  149.45 |
| UBLOX_C030_U201     | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      | 1054.79 |
| UBLOX_EVK_ODIN_W2   | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  148.41 |
| UBLOX_EVK_ODIN_W2   | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  476.82 |
+---------------------+-------------------------------------------------+---------+---------+


[2018-12-18 23:32:06] INFO: TEST FINISHED
```

### CODE REVIEW

**Comment by screamerbg** [comment]
Detailed test results 
[pdmc-v2.1.0-2018-12-18 21-26-09.zip](https://github.com/ARMmbed/simple-mbed-cloud-client/files/2692674/pdmc-v2.1.0-2018-12-18.21-26-09.zip)

**Comment by screamerbg** [comment]
CC @JanneKiiskila

**Comment by screamerbg** [comment]
Results with PDMC 2.1.1

```
2018-12-20 16:59:35 TEST SUMMARY PER TARGET:
+---------------------+-------------------------------------------------+---------+---------+
| target              | test suite                                      | result  |    time |
+---------------------+-------------------------------------------------+---------+---------+
| DISCO_F413ZH        | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   78.31 |
| DISCO_F413ZH        | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  172.16 |
| DISCO_F746NG        | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  112.11 |
| DISCO_F746NG        | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  184.69 |
| DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   85.76 |
| DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  170.41 |
| EFM32GG11_STK3701   | simple-mbed-cloud-client-tests-dev_mgmt-connect | TIMEOUT |  268.83 |
| EFM32GG11_STK3701   | simple-mbed-cloud-client-tests-dev_mgmt-update  | TIMEOUT |  391.98 |
| GR_LYCHEE           | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   94.95 |
| GR_LYCHEE           | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  343.77 |
| K64F                | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  189.36 |
| K64F                | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  176.32 |
| K66F                | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   87.56 |
| K66F                | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  166.19 |
| MTB_MXCHIP_EMW3166  | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  100.97 |
| MTB_MXCHIP_EMW3166  | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  239.67 |
| MTB_USI_WM_BN_BM_22 | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  110.49 |
| MTB_USI_WM_BN_BM_22 | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  278.26 |
| NUCLEO_F207ZG       | MISSING                                         | MISSING |     0.0 |
| NUCLEO_F429ZI       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |    79.8 |
| NUCLEO_F429ZI       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  166.06 |
| NUCLEO_F746ZG       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   69.53 |
| NUCLEO_F746ZG       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  153.89 |
| NUCLEO_F767ZI       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   69.53 |
| NUCLEO_F767ZI       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |   146.4 |
| NUMAKER_IOT_M487    | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |    58.8 |
| NUMAKER_IOT_M487    | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  173.36 |
| NUMAKER_PFM_M487    | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   64.91 |
| NUMAKER_PFM_M487    | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  132.55 |
| NUMAKER_PFM_NUC472  | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  141.86 |
| NUMAKER_PFM_NUC472  | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  218.93 |
| REALTEK_RTL8195AM   | simple-mbed-cloud-client-tests-dev_mgmt-connect | TIMEOUT |  304.81 |
| REALTEK_RTL8195AM   | simple-mbed-cloud-client-tests-dev_mgmt-update  | TIMEOUT | 1864.36 |
| SDT64B              | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |   94.89 |
| SDT64B              | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |  180.14 |
| UBLOX_C030_U201     | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  154.78 |
| UBLOX_C030_U201     | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      | 1196.48 |
| UBLOX_EVK_ODIN_W2   | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  171.34 |
| UBLOX_EVK_ODIN_W2   | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      |   489.9 |
+---------------------+-------------------------------------------------+---------+---------+
```

**Comment by MarceloSalazar** [comment]
Great! Let's merge it!

**Comment by JanneKiiskila** [comment]
Great! Now you can start merging in the 2.1.1 and Mbed OS 5.11!

**Comment by screamerbg** [comment]
@JanneKiiskila Mbed OS 5.11 and PDMC 2.1.1 are already merged in https://github.com/ARMmbed/pelion-enablement. Examples will follow soon.

**Pull request merged**
